# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: 'fair-coffer-spangle-birdie'

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  new.kingdomage.org:
    admin_password: 'phobic-baste-statue-bludgeon'
    env:
      db_password: 'abscound-sepal-guise-brant'
